export const GET_USERS = 'GET_USERS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_ASSIGNEE_TASKS = 'GET_ASSIGNEE_TASKS';
export const GET_CREATED_TASKS = 'GET_CREATED_TASKS';
export const GET_FILTERED_ASSIGNEE_TASKS = 'GET_FILTERED_ASSIGNEE_TASKS';
export const GET_FILTERED_CREATED_TASKS = 'GET_FILTERED_CREATED_TASKS';